// src/app/OutputPanel.jsx
import { PauseCircleIcon } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import {
  buildRevenueSummary,
  formatElapsed,
  formatPlainNumber,
  formatPlayCountDisplay,
  formatPlayCountWanFixed,
} from "@/app/app-utils";

function getMetricToneClass(index) {
  const variants = [
    "border-border/80 bg-background text-foreground shadow-[inset_0_1px_0_rgba(255,255,255,0.62),0_8px_18px_-16px_rgba(15,23,42,0.18)]",
    "border-secondary/20 bg-secondary/12 text-foreground",
    "border-primary/20 bg-accent text-accent-foreground",
  ];
  return variants[index % variants.length];
}

function getMetricLabelClass(index) {
  return index % 3 === 0 ? "text-foreground/72" : "opacity-72";
}

function trimTrailingZero(value) {
  return value.replace(/\.?0+$/, "");
}

function formatUnitlessMetricValue(value) {
  const amount = Number(value ?? 0);
  if (!Number.isFinite(amount) || amount <= 0) {
    return "0";
  }
  if (amount >= 100000000) {
    return `${trimTrailingZero((amount / 100000000).toFixed(2))}亿`;
  }
  if (amount >= 10000) {
    return `${trimTrailingZero((amount / 10000).toFixed(1))}万`;
  }
  if (Number.isInteger(amount)) {
    return `${amount}`;
  }
  return trimTrailingZero(amount.toFixed(2));
}

function formatUnitlessMetricRange(minValue, maxValue) {
  return `${formatUnitlessMetricValue(minValue)} - ${formatUnitlessMetricValue(maxValue)}`;
}

function ResultStrip({ metrics, inverted = false }) {
  return (
    <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">
      {metrics.map((metric, index) => {
        const toneIndex = inverted ? index + 2 : index;
        return (
          <div
            key={`${metric.label}-${index}`}
            className={`min-w-0 rounded-[calc(var(--radius)-0.12rem)] border px-2 py-2.5 text-center sm:px-3 ${getMetricToneClass(toneIndex)}`}
          >
            <div className={`text-[10px] sm:text-xs ${getMetricLabelClass(toneIndex)}`}>{metric.label}</div>
            <div className="mt-1 break-words text-sm font-semibold leading-tight sm:text-lg">{metric.value}</div>
          </div>
        );
      })}
    </div>
  );
}

function ResultCard({ title, metrics, insetInverted = false, footer = null }) {
  return (
    <div className="w-full min-w-0 rounded-lg border border-border/80 bg-card p-3 shadow-[0_16px_34px_-30px_rgba(15,23,42,0.16)] sm:p-4">
      <div className="break-words text-[11px] font-medium leading-5 text-foreground/78 sm:text-xs">{title}</div>
      {metrics?.length ? (
        <div className="mt-3">
          <ResultStrip metrics={metrics} inverted={insetInverted} />
        </div>
      ) : null}
      {footer ? <div className="mt-3">{footer}</div> : null}
    </div>
  );
}

export function OutputPanel({
  platform,
  progress,
  currentAction,
  elapsedMs,
  playCountResults,
  playCountSelectedEpisodeCount,
  playCountTotal,
  playCountFailed,
  idResults,
  suspectedOverflowEpisodes = [],
  idSelectedEpisodeCount,
  totalDanmaku,
  totalUsers,
  revenueResults,
  revenueSummary,
  isRunning,
  onCancelStatistics,
}) {
  const resolvedRevenueSummary = revenueSummary || buildRevenueSummary(revenueResults, platform);

  function getPaidCountLabel(drama) {
    if (drama?.platform === "manbo" && drama?.paidCountSource === "pay_count") {
      return "付费人数";
    }
    return "付费用户 ID 数";
  }

  function getSummaryPaidCountLabel(summary) {
    if (summary?.platform === "manbo" && summary?.paidCountSourceSummary === "pay_count") {
      return "总付费人次";
    }
    return "总和去重 ID";
  }

  function getRewardLabel(drama, isSummary = false) {
    if (drama?.platform === "manbo") {
      return "投喂总数（红豆）";
    }
    return isSummary ? "打赏榜总和（钻石）" : "打赏榜累计（钻石）";
  }

  function formatRewardMetricValue(drama) {
    if (drama?.platform === "manbo") {
      return formatUnitlessMetricValue(drama?.diamondValue ?? drama?.rewardTotal);
    }
    return formatUnitlessMetricValue(drama?.rewardCoinTotal ?? drama?.rewardTotal);
  }

  function hasRewardNum(drama) {
    return drama?.platform === "missevan" && drama?.rewardNum != null && Number.isFinite(Number(drama?.rewardNum));
  }

  function shouldShowRevenueRange(drama) {
    if (!drama || drama.failed) {
      return false;
    }
    if (drama.minRevenueYuan == null || drama.maxRevenueYuan == null) {
      return false;
    }
    return Number.isFinite(Number(drama.minRevenueYuan)) && Number.isFinite(Number(drama.maxRevenueYuan));
  }

  function isManboRewardOnlyRevenue(drama) {
    if (drama?.platform !== "manbo") {
      return false;
    }
    if (drama?.summaryRevenueMode === "member_reward" || drama?.revenueType === "member") {
      return true;
    }
    const rewardValue = Number(drama?.diamondValue ?? drama?.rewardTotal ?? 0);
    const titlePrice = Number(drama?.titlePrice ?? drama?.titlePriceTotal ?? 0);
    return rewardValue > 0 && titlePrice <= 0 && !shouldShowRevenueRange(drama);
  }

  function isMissevanRewardOnlyRevenue(drama) {
    if (drama?.platform !== "missevan") {
      return false;
    }
    return Boolean(
      drama?.vipOnlyReward ||
        drama?.summaryRevenueMode === "member_reward" ||
        (!drama?.failed && !drama?.hasSummaryPrice && Number(drama?.rewardTotal ?? 0) > 0)
    );
  }

  function getRevenueLabel(drama) {
    if (isManboRewardOnlyRevenue(drama)) {
      return "收益预估（仅计算投喂，元）";
    }
    if (isMissevanRewardOnlyRevenue(drama)) {
      return "收益预估（仅计算打赏，元）";
    }
    return "收益预估（元）";
  }

  const hasAnyResults = Boolean(
    playCountResults?.length || idResults?.length || revenueResults?.length
  );

  if (!isRunning && !hasAnyResults) {
    return null;
  }

  return (
    <Card className="border-border/80 bg-card shadow-[0_24px_52px_-42px_rgba(15,23,42,0.22)]">
      <CardContent className="flex flex-col gap-5 p-4 sm:p-5">
        <div className="grid gap-3 rounded-lg border border-border/80 bg-background/70 p-3 sm:p-4">
          <div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center">
            <div className="flex min-w-0 flex-col gap-1">
              <div className="text-base font-semibold text-foreground sm:text-lg">{currentAction || "等待执行操作"}</div>
              <div className="text-[11px] text-muted-foreground sm:text-xs">
                <div>处理用时：{formatElapsed(elapsedMs)}</div>
              </div>
            </div>
            <div className="flex shrink-0 items-center justify-end gap-2 text-right">
              <div className="text-lg font-semibold text-foreground sm:text-xl">{progress}%</div>
              {isRunning ? (
                <Badge className="px-3 py-1 text-[11px] sm:text-xs">进行中</Badge>
              ) : (
                <Badge variant="secondary" className="px-3 py-1 text-[11px] sm:text-xs">空闲</Badge>
              )}
              {isRunning ? (
                <Button variant="secondary" size="sm" className="text-[11px] sm:text-xs" onClick={onCancelStatistics}>
                  <PauseCircleIcon data-icon="inline-start" />
                  取消
                </Button>
              ) : null}
            </div>
          </div>
          <Progress value={progress} className="h-3 rounded-full bg-muted" indicatorClassName="bg-primary" />
        </div>

        {playCountResults?.length ? (
          <div className="grid gap-3">
            <ResultCard
              title={`汇总 / 已选 ${playCountSelectedEpisodeCount} 集`}
              insetInverted
              metrics={[
                {
                  label: "总播放量",
                  value: formatPlayCountDisplay(playCountTotal, playCountFailed),
                },
              ]}
            />
            {playCountResults.map((drama) => (
              <ResultCard
                key={`play-${drama.title}`}
                title={`${drama.title} / 已选 ${drama.selectedEpisodeCount} 集`}
                insetInverted={false}
                metrics={[
                  {
                    label: "总播放量",
                    value: formatPlayCountDisplay(drama.playCountTotal, drama.playCountFailed),
                  },
                ]}
              />
            ))}
          </div>
        ) : null}

        {idResults?.length ? (
          <div className="grid gap-3">
            <ResultCard
              title={`汇总 / 已选 ${idSelectedEpisodeCount} 集`}
              metrics={[]}
              footer={
                <div className="grid gap-3">
                  <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">
                    {[
                      { label: "总弹幕数", value: formatPlainNumber(totalDanmaku) },
                      { label: "总去重", value: formatPlainNumber(totalUsers) },
                    ].map((metric, metricIndex) => (
                      <div key={`summary-${metric.label}`} className={`min-w-0 rounded-[calc(var(--radius)-0.12rem)] border px-2 py-2 text-center sm:px-3 ${getMetricToneClass(metricIndex + idResults.length)}`}>
                        <div className={`text-[10px] sm:text-xs ${getMetricLabelClass(metricIndex + idResults.length)}`}>{metric.label}</div>
                        <div className="mt-1 break-words text-sm font-semibold leading-tight sm:text-lg">{metric.value}</div>
                      </div>
                    ))}
                  </div>
                  {suspectedOverflowEpisodes?.length ? (
                    <div className="grid gap-2 rounded-[calc(var(--radius)-0.08rem)] border border-border/80 bg-background/96 p-3 text-foreground">
                      <div className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
                        疑似弹幕溢出分集
                      </div>
                      {suspectedOverflowEpisodes.map((title) => (
                        <div key={`overflow-${title}`} className="text-sm">
                          {title}
                        </div>
                      ))}
                    </div>
                  ) : null}
                </div>
              }
            />
            {idResults.map((drama) => (
              <ResultCard
                key={`id-${drama.title}`}
                title={`${drama.title} / 已选 ${drama.selectedEpisodeCount} 集`}
                metrics={[]}
                footer={
                  <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">
                    {[
                      { label: "总弹幕数", value: formatPlainNumber(drama.danmaku) },
                      { label: "去重 ID 数", value: formatPlainNumber(drama.users) },
                    ].map((metric, metricIndex) => (
                      <div
                        key={`${drama.title}-${metric.label}`}
                        className={`min-w-0 rounded-md border px-2 py-2 text-center sm:px-3 ${getMetricToneClass(metricIndex)}`}
                      >
                        <div className={`text-[10px] sm:text-xs ${getMetricLabelClass(metricIndex)}`}>{metric.label}</div>
                        <div className="mt-1 break-words text-sm font-semibold leading-tight sm:text-lg">{metric.value}</div>
                      </div>
                    ))}
                  </div>
                }
              />
            ))}
          </div>
        ) : null}

        {revenueResults?.length ? (
          <div className="grid gap-3">
            {resolvedRevenueSummary ? (
              <ResultCard
                title={resolvedRevenueSummary.summaryTitle || `汇总 / 已选 ${resolvedRevenueSummary.selectedDramaCount} 部`}
                insetInverted={false}
                metrics={[
                  ...(resolvedRevenueSummary.paidCountSourceSummary === "mixed"
                    ? [
                        { label: "总付费人次", value: resolvedRevenueSummary.failed ? "访问失败" : formatPlainNumber(resolvedRevenueSummary.totalPayCount) },
                        { label: "总和去重 ID", value: resolvedRevenueSummary.failed ? "访问失败" : formatPlainNumber(resolvedRevenueSummary.totalDanmakuPaidUserCount) },
                      ]
                    : [
                        {
                          label: getSummaryPaidCountLabel(resolvedRevenueSummary),
                          value: resolvedRevenueSummary.failed ? "访问失败" : formatPlainNumber(resolvedRevenueSummary.totalPaidUserCount),
                        },
                      ]),
                  {
                    label: "总播放量",
                    value: resolvedRevenueSummary.failed ? "访问失败" : formatPlayCountWanFixed(resolvedRevenueSummary.totalViewCount),
                  },
                  {
                    label: getRewardLabel(resolvedRevenueSummary, true),
                    value: resolvedRevenueSummary.failed
                      ? "访问失败"
                      : formatRewardMetricValue(resolvedRevenueSummary),
                  },
                  ...(hasRewardNum(resolvedRevenueSummary)
                    ? [{ label: "打赏人次", value: formatPlainNumber(resolvedRevenueSummary.rewardNum) }]
                    : []),
                  {
                    label: getRevenueLabel(resolvedRevenueSummary),
                    value: resolvedRevenueSummary.failed
                      ? "预估失败"
                      : shouldShowRevenueRange(resolvedRevenueSummary)
                        ? formatUnitlessMetricRange(resolvedRevenueSummary.minRevenueYuan, resolvedRevenueSummary.maxRevenueYuan)
                        : formatUnitlessMetricValue(resolvedRevenueSummary.estimatedRevenueYuan),
                  },
                ]}
              />
            ) : null}

            {revenueResults.map((drama) => (
              <ResultCard
                key={`revenue-${drama.dramaId}`}
                title={drama.subtitle || `${drama.title} / 单价 ${drama.price || 0} 钻石`}
                insetInverted={false}
                metrics={[
                  {
                    label: getPaidCountLabel(drama),
                    value: drama.failed ? "访问失败" : formatPlainNumber(drama.paidUserCount),
                  },
                  {
                    label: getRewardLabel(drama),
                    value: drama.failed ? "访问失败" : formatRewardMetricValue(drama),
                  },
                  ...(hasRewardNum(drama)
                    ? [{ label: "打赏人数", value: formatPlainNumber(drama.rewardNum) }]
                    : []),
                  {
                    label: getRevenueLabel(drama),
                    value: drama.failed
                      ? "预估失败"
                      : shouldShowRevenueRange(drama)
                        ? formatUnitlessMetricRange(drama.minRevenueYuan, drama.maxRevenueYuan)
                        : formatUnitlessMetricValue(drama.estimatedRevenueYuan),
                  },
                ]}
              />
            ))}
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}

// src/components/OutputPanel.vue
<template>
  <div class="output-panel">
    <div class="output-status-card">
      <div class="status-header">
        <div>
          <div class="status-kicker">运行状态</div>
          <div class="status-text">{{ currentAction || "等待执行操作" }}</div>
          <div class="status-elapsed">处理用时：{{ formatElapsed(elapsedMs) }}</div>
        </div>
        <div class="status-side">
          <div v-if="isRunning" class="status-badge">进行中</div>
          <button
            v-if="isRunning"
            type="button"
            class="status-cancel-btn"
            @click="$emit('cancelStatistics')"
          >
            取消
          </button>
          <div class="status-progress">{{ progress }}%</div>
        </div>
      </div>

      <div class="output-progress">
        <div class="output-progress-bar" :style="{ width: `${progress}%` }"></div>
      </div>
    </div>

    <div v-if="playCountResults.length" class="output-section">
      <div class="output-section-title">播放量统计</div>
      <div class="output-list">
        <div
          v-for="drama in playCountResults"
          :key="`play-${drama.title}`"
          class="output-card"
        >
          <div class="output-card-title">
            {{ drama.title }} / 已选 {{ drama.selectedEpisodeCount }} 集
          </div>
          <div class="output-stat-label">总播放量</div>
          <div class="output-stat-value">
            {{ formatPlayCountDisplay(drama.playCountTotal, drama.playCountFailed) }}
          </div>
        </div>

        <div class="output-summary-card">
          <div class="output-card-title">汇总 / 已选 {{ playCountSelectedEpisodeCount }} 集</div>
          <div class="output-stat-label">总播放量</div>
          <div class="output-stat-value">
            {{ formatPlayCountDisplay(playCountTotal, playCountFailed) }}
          </div>
        </div>
      </div>
    </div>

    <div v-if="idResults.length" class="output-section">
      <div class="output-section-title">弹幕与去重 ID 统计</div>
      <div class="output-list">
        <div
          v-for="drama in idResults"
          :key="`id-${drama.title}`"
          class="output-card"
        >
          <div class="output-card-title">
            {{ drama.title }} / 已选 {{ drama.selectedEpisodeCount }} 集
          </div>
          <div class="output-stats">
            <div>
              <div class="output-stat-label">总弹幕数</div>
              <div class="output-stat-value">{{ drama.danmaku }}</div>
            </div>
            <div>
              <div class="output-stat-label">去重 ID 数</div>
              <div class="output-stat-value">{{ drama.users }}</div>
            </div>
          </div>
        </div>

        <div class="output-summary-card">
          <div class="output-card-title">汇总 / 已选 {{ idSelectedEpisodeCount }} 集</div>
          <div class="output-stats">
            <div>
              <div class="output-stat-label">总弹幕数</div>
              <div class="output-stat-value">{{ totalDanmaku }}</div>
            </div>
            <div>
              <div class="output-stat-label">去重 ID 数</div>
              <div class="output-stat-value">{{ totalUsers }}</div>
            </div>
          </div>
          <div
            v-if="Array.isArray(suspectedOverflowEpisodes) && suspectedOverflowEpisodes.length"
            class="output-overflow-list"
          >
            <div class="output-stat-label">疑似弹幕溢出分集</div>
            <div
              v-for="title in suspectedOverflowEpisodes"
              :key="`overflow-id-${title}`"
              class="output-overflow-item"
            >
              {{ title }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="revenueResults.length" class="output-section">
      <div class="output-section-title">最低收益预估</div>
      <div class="output-list">
        <div
          v-for="drama in revenueResults"
          :key="`revenue-${drama.dramaId}`"
          class="output-card"
        >
          <div class="output-card-title">
            {{ drama.subtitle || `${drama.title} / 单价 ${formatDiamond(drama.price)}` }}
          </div>
          <div class="output-stats">
            <div>
              <div class="output-stat-label">{{ getPaidCountLabel(drama) }}</div>
              <div class="output-stat-value">
                {{ drama.failed ? "访问失败" : drama.paidUserCount }}
              </div>
            </div>
            <div>
              <div class="output-stat-label">
                {{ getRewardLabel(drama) }}
              </div>
              <div class="output-stat-value">
                {{
                  drama.failed
                    ? "访问失败"
                    : formatRewardValue(
                        drama.platform,
                        drama.platform === "manbo" ? drama.diamondValue : drama.rewardCoinTotal
                      )
                }}
              </div>
            </div>
            <div v-if="hasRewardNum(drama)">
              <div class="output-stat-label">打赏人数</div>
              <div class="output-stat-value">{{ formatPlainCountValue(drama.rewardNum) }}</div>
            </div>
          </div>
          <div class="output-revenue-line">
            <div class="output-stat-label">{{ getRevenueLabel(drama) }}</div>
            <div class="output-stat-value">
              {{
                drama.failed
                  ? "预估失败"
                  : shouldShowRevenueRange(drama)
                    ? formatRevenueRange(drama.minRevenueYuan, drama.maxRevenueYuan)
                    : formatRevenue(drama.estimatedRevenueYuan)
              }}
            </div>
          </div>
        </div>

        <div v-if="revenueSummary" class="output-summary-card">
          <div class="output-card-title">
            {{ revenueSummary.summaryTitle || `汇总 / 已选 ${revenueSummary.selectedDramaCount} 部` }}
          </div>
          <div class="output-stats">
            <div v-if="revenueSummary.paidCountSourceSummary === 'mixed'">
              <div class="output-stat-label">总付费人次</div>
              <div class="output-stat-value">
                {{
                  revenueSummary.failed
                    ? "访问失败"
                    : formatPlainCountValue(revenueSummary.totalPayCount)
                }}
              </div>
            </div>
            <div v-if="revenueSummary.paidCountSourceSummary === 'mixed'">
              <div class="output-stat-label">总和去重 ID</div>
              <div class="output-stat-value">
                {{
                  revenueSummary.failed
                    ? "访问失败"
                    : formatPlainCountValue(revenueSummary.totalDanmakuPaidUserCount)
                }}
              </div>
            </div>
            <div v-else>
              <div class="output-stat-label">{{ getSummaryPaidCountLabel(revenueSummary) }}</div>
              <div class="output-stat-value">
                {{
                  revenueSummary.failed
                    ? "访问失败"
                    : formatPlainCountValue(revenueSummary.totalPaidUserCount)
                }}
              </div>
            </div>
            <div>
              <div class="output-stat-label">总播放量</div>
              <div class="output-stat-value">
                {{ revenueSummary.failed ? "访问失败" : formatPlayCountWanFixed(revenueSummary.totalViewCount) }}
              </div>
            </div>
            <div>
              <div class="output-stat-label">
                {{ getRewardLabel(revenueSummary, true) }}
              </div>
              <div class="output-stat-value">
                {{
                  revenueSummary.failed
                    ? "访问失败"
                    : formatRewardValue(revenueSummary.platform, revenueSummary.rewardTotal)
                }}
              </div>
            </div>
            <div v-if="hasRewardNum(revenueSummary)">
              <div class="output-stat-label">打赏人次</div>
              <div class="output-stat-value">{{ formatPlainCountValue(revenueSummary.rewardNum) }}</div>
            </div>
          </div>
          <div class="output-revenue-line">
            <div class="output-stat-label">收益预估</div>
            <div class="output-stat-value">
              {{
                revenueSummary.failed
                  ? "预估失败"
                  : shouldShowRevenueRange(revenueSummary)
                    ? formatRevenueRange(revenueSummary.minRevenueYuan, revenueSummary.maxRevenueYuan)
                    : formatRevenue(revenueSummary.estimatedRevenueYuan)
              }}
            </div>
          </div>
          <div
            v-if="Array.isArray(revenueSummary.suspectedOverflowEpisodes) && revenueSummary.suspectedOverflowEpisodes.length"
            class="output-overflow-list"
          >
            <div class="output-stat-label">疑似弹幕溢出分集</div>
            <div
              v-for="title in revenueSummary.suspectedOverflowEpisodes"
              :key="`overflow-revenue-${title}`"
              class="output-overflow-item"
            >
              {{ title }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  emits: ["cancelStatistics"],
  props: {
    progress: Number,
    currentAction: String,
    elapsedMs: Number,
    playCountResults: Array,
    playCountSelectedEpisodeCount: Number,
    playCountTotal: Number,
    playCountFailed: Boolean,
    idResults: Array,
    suspectedOverflowEpisodes: {
      type: Array,
      default: () => [],
    },
    idSelectedEpisodeCount: Number,
    totalDanmaku: Number,
    totalUsers: Number,
    revenueResults: Array,
    revenueSummary: Object,
    isRunning: Boolean,
  },
  methods: {
    getPaidCountLabel(drama) {
      if (drama?.platform === "manbo" && drama?.paidCountSource === "pay_count") {
        return "付费人数";
      }
      return "付费用户 ID 数";
    },
    getSummaryPaidCountLabel(summary) {
      if (summary?.platform === "manbo") {
        if (summary?.paidCountSourceSummary === "pay_count") {
          return "总付费人次";
        }
      }
      return "总和去重 ID";
    },
    getRewardLabel(drama, isSummary = false) {
      if (drama?.platform === "manbo") {
        return "投喂总数";
      }
      return isSummary ? "打赏榜总和" : "打赏榜累计";
    },
    formatRewardValue(platform, value) {
      const amount = Number(value ?? 0);
      return platform === "manbo" ? `${amount} 红豆` : `${amount} 钻石`;
    },
    hasRewardNum(drama) {
      return drama?.platform === "missevan"
        && drama?.rewardNum != null
        && Number.isFinite(Number(drama?.rewardNum));
    },
    formatPlainCountValue(value) {
      const count = Number(value ?? 0);
      if (!Number.isFinite(count)) {
        return "0";
      }
      return `${Math.trunc(count)}`;
    },
    shouldShowRevenueRange(drama) {
      if (!drama || drama.failed) {
        return false;
      }
      if (drama.minRevenueYuan == null || drama.maxRevenueYuan == null) {
        return false;
      }
      return Number.isFinite(Number(drama.minRevenueYuan))
        && Number.isFinite(Number(drama.maxRevenueYuan));
    },
    getRevenueLabel(drama) {
      return drama?.vipOnlyReward ? "预估收益（仅计算打赏）" : "预估收益";
    },
    formatPlayCountDisplay(value, failed) {
      if (failed) {
        return "部分分集统计失败";
      }
      const count = Number(value ?? 0);
      if (!Number.isFinite(count) || count <= 0) {
        return "0";
      }
      if (count < 10000) {
        return `${count}`;
      }
      if (count < 100000000) {
        return `${(count / 10000).toFixed(1)}万`;
      }
      return `${(count / 100000000).toFixed(2)}亿`;
    },
    formatPlayCountWanFixed(value) {
      const count = Number(value ?? 0);
      if (!Number.isFinite(count) || count <= 0) {
        return "0.0万";
      }
      return `${(count / 10000).toFixed(1)}万`;
    },
    formatDiamond(value) {
      return `${Number(value ?? 0)} 钻石`;
    },
    formatRevenue(value) {
      const amount = Number(value ?? 0);
      if (!Number.isFinite(amount) || amount <= 0) {
        return "0 元";
      }
      if (amount >= 100000000) {
        return `${(amount / 100000000).toFixed(2)} 亿元`;
      }
      if (amount >= 10000) {
        return `${(amount / 10000).toFixed(1)} 万元`;
      }
      if (Number.isInteger(amount)) {
        return `${amount} 元`;
      }
      return `${amount.toFixed(2).replace(/\.?0+$/, "")} 元`;
    },
    formatRevenueRange(minValue, maxValue) {
      return `${this.formatRevenue(minValue)} - ${this.formatRevenue(maxValue)}`;
    },
    formatElapsed(value) {
      const totalSeconds = Math.max(0, Math.floor(Number(value ?? 0) / 1000));
      const hours = Math.floor(totalSeconds / 3600);
      const minutes = Math.floor((totalSeconds % 3600) / 60);
      const seconds = totalSeconds % 60;

      if (hours > 0) {
        return `${hours}h ${String(minutes).padStart(2, "0")}m ${String(seconds).padStart(2, "0")}s`;
      }

      return `${minutes}m ${String(seconds).padStart(2, "0")}s`;
    },
  },
};
</script>

<style scoped>
.output-panel {
  display: grid;
  gap: 16px;
  padding: 18px;
}

.output-status-card,
.output-card,
.output-summary-card {
  padding: 16px;
  background: rgba(255, 255, 255, 0.82);
  border: 1px solid rgba(29, 53, 87, 0.08);
  border-radius: 18px;
}

.status-header {
  display: flex;
  gap: 12px;
  align-items: flex-start;
  justify-content: space-between;
}

.status-kicker {
  color: var(--text-muted);
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.status-text {
  margin-top: 6px;
  font-size: 18px;
  font-weight: 700;
  line-height: 1.4;
}

.status-elapsed {
  margin-top: 8px;
  color: var(--text-muted);
  font-size: 13px;
}

.status-side {
  display: inline-flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 8px;
  text-align: right;
}

.status-badge {
  display: inline-flex;
  padding: 6px 10px;
  color: #fff;
  font-size: 12px;
  font-weight: 700;
  background: linear-gradient(135deg, #2f5d7c, #244962);
  border-radius: 999px;
}

.status-cancel-btn {
  min-height: 34px;
  padding: 6px 14px;
  color: #8a2d18;
  font-size: 13px;
  font-weight: 700;
  cursor: pointer;
  background: rgba(255, 241, 235, 0.9);
  border: 1px solid rgba(207, 92, 54, 0.2);
  border-radius: 999px;
}

.status-cancel-btn:hover {
  background: rgba(255, 233, 224, 0.96);
}

.status-progress {
  font-size: 20px;
  font-weight: 800;
}

.output-progress {
  height: 10px;
  margin-top: 16px;
  overflow: hidden;
  background: rgba(29, 53, 87, 0.08);
  border-radius: 999px;
}

.output-progress-bar {
  height: 100%;
  background: linear-gradient(135deg, var(--accent), var(--accent-strong));
  border-radius: inherit;
  transition: width 0.2s ease;
}

.output-section {
  display: grid;
  gap: 12px;
}

.output-section-title {
  font-size: 16px;
  font-weight: 800;
}

.output-list {
  display: grid;
  gap: 12px;
}

.output-card-title {
  font-size: 15px;
  font-weight: 800;
  line-height: 1.5;
}

.output-stats {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  margin-top: 14px;
}

.output-stat-label {
  color: var(--text-muted);
  font-size: 12px;
  font-weight: 700;
}

.output-stat-value {
  margin-top: 6px;
  font-size: 18px;
  font-weight: 800;
  line-height: 1.3;
}

.output-revenue-line {
  margin-top: 14px;
  padding-top: 14px;
  border-top: 1px solid rgba(29, 53, 87, 0.08);
}

.output-overflow-list {
  display: grid;
  gap: 6px;
  margin-top: 14px;
  padding-top: 14px;
  border-top: 1px solid rgba(29, 53, 87, 0.08);
}

.output-overflow-item {
  font-size: 14px;
  line-height: 1.5;
}

@media (max-width: 640px) {
  .output-panel {
    padding: 14px;
  }

  .status-header,
  .output-stats {
    grid-template-columns: 1fr;
  }

  .status-header {
    display: grid;
  }

  .status-side {
    display: grid;
    grid-template-columns: 1fr auto;
    align-items: center;
    text-align: left;
  }

  .status-badge {
    justify-self: start;
  }

  .status-cancel-btn {
    justify-self: end;
  }

  .status-progress {
    grid-column: 1 / -1;
    justify-self: start;
  }
}
</style>
